apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-app
  namespace: dev
  labels:
    app: playground-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground-app
  template:
    metadata:
      labels:
        app: playground-app
    spec:
      containers:
        - name: playground
          image: wil42/playground:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: playground-app
  namespace: dev
  labels:
    app: playground-app
spec:
  selector:
    app: playground-app
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
