Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"
  
  config.vm.synced_folder ".", "/vagrant",
    disabled: true
  config.vm.synced_folder "./scripts", "/scripts",
    create: true

  config.vm.define "etaquetS" do |control|
    control.vm.hostname = "etaquetS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.network "forwarded_port", guest: 6443, host: 16443
    control.vm.provider "libvirt" do |v|
      v.memory = "512"
      v.cpus = 1
    end
    control.vm.provision "shell", inline: <<-SHELL
      apt-get -y update; apt-get -y install curl
      curl -sfL https://get.k3s.io | sh -s - server --flannel-backend vxlan --token "password"
    SHELL
  end
end
