token = ENV["K3S_TOKEN"] || "password"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"
  # config.vm.box_url = "https://vagrantcloud.com/debian/boxes/bookworm64/versions/12.20250126.1/providers/virtualbox/amd64/vagrant.box"
  
  config.vm.synced_folder ".", "/vagrant",
    disabled: true
  config.vm.synced_folder "./scripts", "/scripts",
    create: true,
    type: "rsync"

  config.vm.define "artgirarS" do |control|
    control.vm.hostname = "artgirarS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "libvirt" do |v|
      v.memory = 512
      v.cpus = 1
      v.driver = "kvm"
    end
    control.vm.provision "shell", env: {"K3S_TOKEN" => token}, inline: <<-SHELL
      apt-get -y update; apt-get -y install curl
      curl -sfL https://get.k3s.io | K3S_TOKEN=$K3S_TOKEN sh -s - server
    SHELL
  end

  config.vm.define "artgirarSW" do |control|
    control.vm.hostname = "artgirarSW"
    control.vm.network "private_network", ip: "192.168.56.111"
    control.vm.provider "libvirt" do |v|
      v.memory = 512
      v.cpus = 1
      v.driver = "kvm"
    end
    control.vm.provision "shell", env: {"K3S_TOKEN" => token}, inline: <<-SHELL
      apt-get -y update; apt-get -y install curl
      curl -sfL https://get.k3s.io | K3S_TOKEN=$K3S_TOKEN sh -s - agent --server "https://192.168.56.110:6443"
    SHELL
  end
end
