Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_url = "https://vagrantcloud.com/debian/boxes/bookworm64/versions/12.20250126.1/providers/virtualbox/amd64/vagrant.box"
  
  config.vm.synced_folder ".", "/vagrant",
    disabled: true
  config.vm.synced_folder "./scripts", "/scripts",
    create: true

  config.vm.define "artgirarS" do |control|
    control.vm.hostname = "artgirarS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.network "forwarded_port", guest: 6443, host: 16443
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "artgirarS"]
      v.memory = "2048"
      v.cpus = 2
    end
    control.vm.provision "shell", inline: <<-SHELL
      apt-get -y update; apt-get -y install curl
      curl -sfL https://get.k3s.io | sh -s - server --flannel-backend vxlan --token "password"
    SHELL
  end

  config.vm.define "artgirarSW" do |control|
    control.vm.hostname = "artgirarSW"
    control.vm.network "private_network", ip: "192.168.56.111"
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "artgirarSW"]
      v.memory = "2048"
      v.cpus = 2
    end
    control.vm.provision "shell", inline: <<-SHELL
      apt-get -y update; apt-get -y install curl
      curl -sfL https://get.k3s.io | sh -s - agent --server "https://192.168.56.110:6443" --token "password"
    SHELL
  end
end
